In [1]:
import sys
sys.path.append('../')
# import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
# import torch
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import r2_score
from tqdm import tqdm
import pandas as pd
# import skdim
from src.comparison.point_clouds import generate_point_cloud
from src.comparison.curvature import compute_sectional_curvature
from src.comparison.abby_curvature import scalar_curvature_est
from src.comparison.diffusion_curvature import diffusion_curvature
from src.comparison.experiments import do_experiment

In [2]:
do_experiment('torus', True, 'plots/torus', noise=0., max_min_num=120, use_cross=True)

  0%|          | 0/5000 [00:00<?, ?it/s]

> /gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/sheaf-neural-network/src/comparison/curvature.py(68)compute_sectional_curvature()
     66 
     67     import pdb; pdb.set_trace()
---> 68     if use_cross:
     69         O2 = np.cross(O[0], O[1])
     70     else:

array([[ 0.82122341,  0.48775678, -0.29611725],
       [ 0.16317462, -0.69802421, -0.69723472],
       [ 0.54677797, -0.52426665,  0.65282335]])
*** NameError: name 'tau_nbhd' is not defined
array([[-0.49754241,  0.50042606,  0.232372  ],
       [-0.4834744 ,  0.49007445,  0.20866759],
       [-0.5251518 ,  0.48727295,  0.24534105],
       ...,
       [-0.73371054, -0.30223348, -0.31303609],
       [-1.30309824,  0.11349034, -0.21387357],
       [-1.36213516,  0.10779487, -0.07987872]])
array([[-0.49754241,  0.50042606,  0.232372  ],
       [-0.4834744 ,  0.49007445,  0.20866759],
       [-0.5251518 ,  0.48727295,  0.24534105],
       ...,
       [-0.73371054, -0.30223348, -0.31303609],
       [-1.30309824,  0.11349034, -0.21387

  0%|          | 0/5000 [01:15<?, ?it/s]


In [3]:
ti = np.random.rand(10,3)

In [4]:
ti

array([[0.38959525, 0.01510745, 0.89827307],
       [0.527044  , 0.84980226, 0.0599047 ],
       [0.22745811, 0.25938   , 0.38669149],
       [0.80286637, 0.38655787, 0.20465353],
       [0.06499026, 0.07949175, 0.76004721],
       [0.44480299, 0.72618112, 0.68228712],
       [0.13536246, 0.14288793, 0.75534202],
       [0.72126829, 0.37803077, 0.07742226],
       [0.01209802, 0.28815695, 0.00922227],
       [0.23007262, 0.41950074, 0.12141577]])

In [14]:
np.square(np.linalg.norm(ti[2]))

AxisError: axis 1 is out of bounds for array of dimension 0

In [12]:
np.square(ti[1]).sum()

0.2685454859668309

In [15]:
np.square(ti).sum(axis=1)

array([0.95890719, 1.00352783, 0.26854549, 0.83590447, 0.58821443,
       1.19070444, 0.60928152, 0.66912942, 0.08326584, 0.24365607])

In [25]:
O2 = np.random.rand(3)
tau_nbrs = np.random.rand(10,3)
ti = tau_nbrs[1:] - tau_nbrs[0]
norms = np.square(ti).sum(axis=1)
tensor_all2 = 2 * (O2 * ti).sum(axis=1) / norms

tensor_all = []
for i in np.arange(1, len(tau_nbrs)):
    tensor = 2 * (sum(O2 *  (tau_nbrs[i] - tau_nbrs[0])))/np.linalg.norm(tau_nbrs[i] - tau_nbrs[0])**2
    tensor_all.append(tensor)
    

In [26]:
tensor_all2

array([3.57381037, 0.33359788, 0.07753854, 2.48881756, 0.85425387,
       3.98839383, 2.33813761, 1.33899509, 1.33942672])

In [27]:
tensor_all

[3.573810374419844,
 0.3335978771539343,
 0.07753854386391718,
 2.4888175601073894,
 0.8542538737798661,
 3.9883938266685477,
 2.3381376111117516,
 1.3389950915746667,
 1.3394267213211077]

In [21]:
norms

array([0.        , 0.45935563, 0.66268585, 0.81223824, 0.87073795,
       0.34534742, 1.44425899, 0.25037212, 0.35415256, 0.30480286])